# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/lyon-ml-api:$COMMIT_SHA', 
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/lyon-ml-api:$COMMIT_SHA'
    ]
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'lyon-ml-api',
      '--image', 'gcr.io/$PROJECT_ID/lyon-ml-api:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '900',
      '--max-instances', '10',
      '--concurrency', '80',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
